- name: Deploy application
  hosts: webservers
  become: yes
  tasks:
    - name: install  apache2 server
      apt:
        name: apache2
        state: present
    - name: Copy app files
      copy:
        src: sample-app/
        dest: /var/www/html/
    - name: Restart web server
      service:
        name: apache2
        state: restarted
