- name: Deploy application
  hosts: webservers
  become: yes
  tasks:
    - name: Copy app files
      copy:
        src: /var/lib/jenkins/workspace/sample-app/
        dest: /var/www/html/
    - name: Restart web server
      service:
        name: apache2
        state: restarted
